# https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
  - package-ecosystem: github-actions
    directory: /
    labels:
      - "🤖 Dependencies"
    schedule:
      interval: daily
